Fix the bug of SubPlan PlaceHolderVar (#40)
### Context

At the commit 50239de1, Heikki allowed multiple SubPlan references to a
single subplan,
which reduced the duplicate gang creation  of the same SubPlan, such as:

```sql
create table foo(a int, b int);
create table bar(c int, d varchar);
create table buz(i int);

SELECT bar.c FROM bar, foo WHERE foo.b = (
SELECT max(i) FROM buz WHERE bar.c = 9) AND foo.b = bar.d::int4;
```

In Greenplum 6, the query plan will be:

```sql
-- GP6
explain (costs off) SELECT bar.c FROM bar, foo WHERE 
    foo.b = (SELECT max(i) FROM buz WHERE bar.c = 9) AND foo.b = bar.d::int4;
                                          QUERY PLAN                                           
--------------------------------------------------------------------------------
 Gather Motion 3:1  (slice4; segments: 3)
   ->  Hash Join
         Hash Cond: ((SubPlan 1) = foo.b)
         ->  Broadcast Motion 3:3  (slice2; segments: 3)
               ->  Seq Scan on bar
                     Filter: ((SubPlan 1) = (d)::integer)
                     SubPlan 1  (slice2; segments: 3)
                       ->  Aggregate
                             ->  Result
                                   One-Time Filter: (bar.c = 9)
                                   ->  Result
                                         ->  Materialize
                                               ->  Broadcast Motion 3:3  (slice1; segments: 3)
                                                     ->  Seq Scan on buz
         ->  Hash
               ->  Seq Scan on foo
         SubPlan 1  (slice4; segments: 3)
           ->  Aggregate
                 ->  Result
                       One-Time Filter: (bar.c = 9)
                       ->  Result
                             ->  Materialize
                                   ->  Broadcast Motion 3:3  (slice3; segments: 3)
                                         ->  Seq Scan on buz
 Optimizer: Postgres query optimizer
```

As we can see, the same SubPlan will be executed twice at different
slice(slice 2 and slice 4).

In Greenplum 7, it'll be referenced by only once:

```sql
-- GP7
postgres=# explain (COSTS OFF) SELECT  bar.c FROM bar, foo WHERE 
    foo.b = (SELECT max(i) FROM buz WHERE bar.c = 9) AND foo.b = bar.d::int4;
                                       QUERY PLAN                                        
-------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Hash Join
         Hash Cond: (((SubPlan 1)) = foo.b)
         ->  Broadcast Motion 3:3  (slice2; segments: 3)
               ->  Seq Scan on bar
                     Filter: ((SubPlan 1) = (d)::integer)
                     SubPlan 1
                       ->  Aggregate
                             ->  Result
                                   One-Time Filter: (bar.c = 9)
                                   ->  Materialize
                                         ->  Broadcast Motion 3:3  (slice3; segments: 3)
                                               ->  Seq Scan on buz
         ->  Hash
               ->  Seq Scan on foo
 Optimizer: Postgres-based planner
```

### Issues

But this patch wasn't perfect, in some corner case, it'll throw
assertion failure and other error message:

```sql
create table foo(a int, b int);
create table bar(c int, d int);
create table buz(i int, j int);

explain select * from foo
where EXISTS (
    select * from bar where
        case when EXISTS (select foo.a from buz where bar.d is NULL)
        then 0 else 1 end
        = bar.c
);

FATAL:  Unexpected internal error (assert.c:44)
DETAIL:  FailedAssertion("!(root->hasLateralRTEs)", File: "initsplan.c", Line: 1714)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

And if we changed the data type of those tables, it'll throw another error:

```sql
drop table foo;
drop table bar;
drop table buz;

create table foo (a varchar(30));
create table bar (c varchar(20));
create table buz (i varchar(20), j varchar(20));

explain select c
from bar
left join buz on bar.c = (
case when buz.j in (select a from foo) 
then buz.j ELSE '' END );

ERROR:  could not find hash distribution key expressions in target list (createplan.c:8187)
```

The root cause lies in the fact that `pull_varnos()` does not process
SubPlans. As a result, the patch introduced by Greenplum was mistakenly 
treated as having LATERAL semantics, even though that was not actually the case.

### Fix

The fix chosen here is relatively simple—it just crudely closes off a
corner-case scenario.